In [1]:
import pandas as pd
import numpy as np

from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

ModuleNotFoundError: No module named 'sklearn'

In [43]:
import re
import string

def text_temizle1(text):
    #kucuk harf yap
    text = text.lower()
    #parantez içindeki yazıları sil
    text = re.sub('\[.*?\]', '', text)
    #noktalama işaretlerini sil
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    #sayıları sil
    text = re.sub('\w*\d\w*', '', text)
    #3 karakterden kısa olan sözcükleri sil türkçe karakterlerle birlikte
    text = re.sub(r'\b[a-zğüşöçıİĞÜŞÖÇ]{1,2}\b', r'',text)
    return text

In [2]:
dataFrame = pd.read_csv("film_Series.csv")
dataFrame.head(3)

ID                        Name  Date Rate    Votes  \
0   0              No Time to Die  2021  7.6  107,163   
1   1   The Many Saints of Newark  2021  6.4   27,145   
2   2  Venom Let There Be Carnage  2021  6.4   30,443   

                         Genre  Duration  Type    Nudity  Violence Profanity  \
0  Action, Adventure, Thriller       163  Film      Mild  Moderate      Mild   
1                 Crime, Drama       120  Film  Moderate    Severe    Severe   
2    Action, Adventure, Sci-Fi        97  Film      None  Moderate  Moderate   

    Alcohol Frightening  
0      Mild    Moderate  
1  Moderate    Moderate  
2      Mild    Moderate

In [4]:
columns = ['Name','Votes','Rate','Duration','Genre','Type','Nudity','Violence','Profanity','Alcohol','Frightening']

In [5]:
dataFrame[columns].head(3)

Name    Votes Rate  Duration  \
0              No Time to Die  107,163  7.6       163   
1   The Many Saints of Newark   27,145  6.4       120   
2  Venom Let There Be Carnage   30,443  6.4        97   

                         Genre  Type    Nudity  Violence Profanity   Alcohol  \
0  Action, Adventure, Thriller  Film      Mild  Moderate      Mild      Mild   
1                 Crime, Drama  Film  Moderate    Severe    Severe  Moderate   
2    Action, Adventure, Sci-Fi  Film      None  Moderate  Moderate      Mild   

  Frightening  
0    Moderate  
1    Moderate  
2    Moderate

In [6]:
dataFrame.isnull().values.any()

False

In [12]:
def get_important_features(data):
    important_features = []
    for i in range(0, data.shape[0]):
        important_features.append(data['Name'][i] + ' ' + data['Votes'][i] + ' ' + data['Rate'][i] + ' ' + data['Duration'][i] + ' ' + data['Genre'][i] + ' ' + data['Type'][i] + ' ' + data['Nudity'][i] + ' ' + data['Violence'][i] + ' ' + data['Profanity'][i] + ' ' + data['Alcohol'][i] + ' ' + data['Frightening'][i])
        
    return important_features

In [14]:
dataFrame['important_features'] = get_important_features(dataFrame)
dataFrame.head(3)

TypeError: can only concatenate str (not "numpy.int64") to str

In [62]:
dataClean = pd.DataFrame(dataFrame.important_features.apply(text_temizle1))
dataClean

important_features
0      time  die     action adventure thriller film ...
1     the many saints  newark     crime drama film m...
2     venom let there  carnage     action adventure ...
3     ted lasso     comedy drama sport series mild n...
4     free guy     action adventure comedy film mild...
...                                                 ...
4815  the human centipede  full sequence     horror ...
4816  double indemnity     crime drama filmnoir film...
4817  before the devil knows youre dead     crime dr...
4818  queen bees     comedy drama romance film none ...
4819  death race     action scifi thriller film mild...

[4820 rows x 1 columns]

In [8]:
cm = CountVectorizer().fit_transform(dataFrame['important_features'])

In [9]:
cs = cosine_similarity(cm)
print(cs)

[[1.         0.28022427 0.48038446 ... 0.14322297 0.26995276 0.4949134 ]
 [0.28022427 1.         0.41666667 ... 0.55901699 0.23414645 0.37463432]
 [0.48038446 0.41666667 1.         ... 0.1490712  0.37463432 0.42146362]
 ...
 [0.14322297 0.55901699 0.1490712  ... 1.         0.16754156 0.4607393 ]
 [0.26995276 0.23414645 0.37463432 ... 0.16754156 1.         0.21052632]
 [0.4949134  0.37463432 0.42146362 ... 0.4607393  0.21052632 1.        ]]


In [10]:
cs.shape

(4820, 4820)

In [34]:
title = 'The Human Centipede First Sequence'

movie_id = dataFrame[dataFrame.Name == title]['Unnamed: 0'].values[0]

In [35]:
movie_id

1216

In [36]:
scores = list(enumerate(cs[movie_id]))

In [37]:
sorted_scores = sorted(scores, key = lambda x:x[1], reverse = True)
sorted_scores = sorted_scores[1:]

In [38]:
print(sorted_scores)

[(4159, 0.7744030926623663), (4321, 0.746003846592251), (3971, 0.7112867591590193), (4266, 0.7112867591590193), (4815, 0.7092993656151906), (576, 0.6993786061802354), (4013, 0.6993786061802354), (1112, 0.6956521739130436), (1517, 0.6956521739130436), (2358, 0.6956521739130436), (2674, 0.6956521739130436), (1686, 0.6825236327899352), (1921, 0.6825236327899352), (2706, 0.6825236327899352), (3404, 0.6825236327899352), (4151, 0.6825236327899352), (1579, 0.6821865008193588), (694, 0.6810052246069991), (3100, 0.681005224606999), (2556, 0.6698938453032356), (4400, 0.6697108225289159), (647, 0.6697108225289158), (40, 0.6672461249826394), (173, 0.6672461249826394), (188, 0.6672461249826394), (1828, 0.6672461249826394), (2929, 0.6672461249826394), (3786, 0.6672461249826394), (286, 0.6668313367115807), (1219, 0.6668313367115807), (3058, 0.6668313367115807), (3713, 0.6668313367115807), (374, 0.6668313367115806), (1234, 0.6668313367115806), (1827, 0.6668313367115806), (3253, 0.6668313367115806), (3

In [39]:
j = 0
print('The 10 most recomended movies to', title, 'are:\n')
for item in sorted_scores:
    movieTitle = dataFrame[dataFrame['Unnamed: 0'] == item[0]]['Name'].values[0]
    print(j+1, movieTitle)
    j+=1
    if j > 9:
        break

The 10 most recomended movies to The Human Centipede First Sequence are:

1 The Human Centipede III Final Sequence
2 Cabin Fever
3 Breach
4 The Perfection
5 The Human Centipede II Full Sequence
6 Grave
7 V/H/S Viral
8 V/H/S
9 Kids
10 The Final Destination
